// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  id: __t.string(),
  name: __t.string(),
  rating: __t.i32(),
  wins: __t.u32(),
  losses: __t.u32(),
  balance: __t.i32(),
  balanceKind: __t.string(),
});
export type Account = __Infer<typeof Account>;

export const AutomationGuard = __t.object("AutomationGuard", {
  identity: __t.identity(),
  joinWindowStartMicros: __t.u64(),
  joinCount: __t.u32(),
  forfeitWindowStartMicros: __t.u64(),
  forfeitCount: __t.u32(),
});
export type AutomationGuard = __Infer<typeof AutomationGuard>;

export const BotMoveCommit = __t.object("BotMoveCommit", {
  id: __t.string(),
  matchId: __t.u64(),
  round: __t.u32(),
  move: __t.u32(),
  salt: __t.string(),
});
export type BotMoveCommit = __Infer<typeof BotMoveCommit>;

export const GameEvent = __t.object("GameEvent", {
  id: __t.u64(),
  matchId: __t.option(__t.u64()),
  round: __t.u32(),
  level: __t.string(),
  event: __t.string(),
  message: __t.string(),
  data: __t.string(),
  createdAtMicros: __t.u64(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const GameTick = __t.object("GameTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GameTick = __Infer<typeof GameTick>;

export const MatchState = __t.object("MatchState", {
  id: __t.u64(),
  p1: __t.identity(),
  p2: __t.identity(),
  p1Name: __t.string(),
  p2Name: __t.string(),
  p1Rating: __t.i32(),
  p2Rating: __t.i32(),
  stake: __t.u32(),
  balanceKind: __t.string(),
  mode: __t.string(),
  room: __t.string(),
  phase: __t.string(),
  status: __t.string(),
  currentRound: __t.u32(),
  p1Score: __t.u32(),
  p2Score: __t.u32(),
  p1Energy: __t.i32(),
  p2Energy: __t.i32(),
  p1BoostEnabled: __t.bool(),
  p2BoostEnabled: __t.bool(),
  p1CommitHash: __t.option(__t.string()),
  p2CommitHash: __t.option(__t.string()),
  p1RevealMove: __t.option(__t.u32()),
  p2RevealMove: __t.option(__t.u32()),
  p1RevealSalt: __t.option(__t.string()),
  p2RevealSalt: __t.option(__t.string()),
  winner: __t.option(__t.identity()),
  replayHash: __t.option(__t.string()),
  createdAtMicros: __t.u64(),
  updatedAtMicros: __t.u64(),
  roundStartedAtMicros: __t.u64(),
  nextRoundReadyAtMicros: __t.option(__t.u64()),
});
export type MatchState = __Infer<typeof MatchState>;

export const PaymentLedger = __t.object("PaymentLedger", {
  paymentId: __t.string(),
  accountId: __t.string(),
  telegramUserId: __t.string(),
  starsAmount: __t.u32(),
  elmAmount: __t.u32(),
  refundableElmAmount: __t.u32(),
  refundedStarsAmount: __t.u32(),
  refundedElmAmount: __t.u32(),
  telegramPaymentChargeId: __t.string(),
  invoicePayload: __t.string(),
  balanceKind: __t.string(),
  status: __t.string(),
  createdAtMicros: __t.u64(),
  paidAtMicros: __t.option(__t.u64()),
  creditedAtMicros: __t.option(__t.u64()),
  refundRequestedAtMicros: __t.option(__t.u64()),
  refundedAtMicros: __t.option(__t.u64()),
  updatedAtMicros: __t.u64(),
});
export type PaymentLedger = __Infer<typeof PaymentLedger>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  rating: __t.i32(),
  wins: __t.u32(),
  losses: __t.u32(),
  balance: __t.i32(),
  balanceKind: __t.string(),
  accountId: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const QueueEntry = __t.object("QueueEntry", {
  identity: __t.identity(),
  name: __t.string(),
  rating: __t.i32(),
  stake: __t.u32(),
  mode: __t.string(),
  room: __t.string(),
  boostEnabled: __t.bool(),
  joinedAtMicros: __t.u64(),
  botFallbackAtMicros: __t.option(__t.u64()),
  accountId: __t.string(),
  balanceKind: __t.string(),
});
export type QueueEntry = __Infer<typeof QueueEntry>;

export const RoundResult = __t.object("RoundResult", {
  id: __t.u64(),
  matchId: __t.u64(),
  round: __t.u32(),
  p1Move: __t.u32(),
  p2Move: __t.u32(),
  p1Energy: __t.i32(),
  p2Energy: __t.i32(),
  p1Score: __t.u32(),
  p2Score: __t.u32(),
  p1Result: __t.string(),
  p2Result: __t.string(),
  overclockSeed: __t.option(__t.string()),
  createdAtMicros: __t.u64(),
});
export type RoundResult = __Infer<typeof RoundResult>;

