// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CommitMoveReducer from "../commit_move_reducer";
import ForfeitMatchReducer from "../forfeit_match_reducer";
import JoinQueueReducer from "../join_queue_reducer";
import LeaveQueueReducer from "../leave_queue_reducer";
import NextRoundReducer from "../next_round_reducer";
import RecordStarsPaymentReducer from "../record_stars_payment_reducer";
import RevealMoveReducer from "../reveal_move_reducer";
import SetProfileReducer from "../set_profile_reducer";
import SubmitMoveReducer from "../submit_move_reducer";

export type CommitMoveParams = __Infer<typeof CommitMoveReducer>;
export type ForfeitMatchParams = __Infer<typeof ForfeitMatchReducer>;
export type JoinQueueParams = __Infer<typeof JoinQueueReducer>;
export type LeaveQueueParams = __Infer<typeof LeaveQueueReducer>;
export type NextRoundParams = __Infer<typeof NextRoundReducer>;
export type RecordStarsPaymentParams = __Infer<typeof RecordStarsPaymentReducer>;
export type RevealMoveParams = __Infer<typeof RevealMoveReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;
export type SubmitMoveParams = __Infer<typeof SubmitMoveReducer>;

