// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  requestId: __t.string().primaryKey().name("request_id"),
  adminTelegramId: __t.string().name("admin_telegram_id"),
  targetAccountId: __t.string().name("target_account_id"),
  balanceKind: __t.string().name("balance_kind"),
  operation: __t.string(),
  previousBalance: __t.i32().name("previous_balance"),
  newBalance: __t.i32().name("new_balance"),
  delta: __t.i32(),
  reason: __t.string(),
  createdAtMicros: __t.u64().name("created_at_micros"),
});
