// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  joinWindowStartMicros: __t.u64().name("join_window_start_micros"),
  joinCount: __t.u32().name("join_count"),
  forfeitWindowStartMicros: __t.u64().name("forfeit_window_start_micros"),
  forfeitCount: __t.u32().name("forfeit_count"),
});
