// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  idempotencyKey: __t.string().primaryKey().name("idempotency_key"),
  accountId: __t.string().name("account_id"),
  balanceKind: __t.string().name("balance_kind"),
  delta: __t.i32(),
  balanceAfter: __t.i32().name("balance_after"),
  reasonKind: __t.string().name("reason_kind"),
  paymentId: __t.option(__t.string()).name("payment_id"),
  matchId: __t.option(__t.u64()).name("match_id"),
  actor: __t.string(),
  createdAtMicros: __t.u64().name("created_at_micros"),
});
