// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  paymentId: __t.string().primaryKey().name("payment_id"),
  accountId: __t.string().name("account_id"),
  telegramUserId: __t.string().name("telegram_user_id"),
  starsAmount: __t.u32().name("stars_amount"),
  elmAmount: __t.u32().name("elm_amount"),
  refundableElmAmount: __t.u32().name("refundable_elm_amount"),
  refundedStarsAmount: __t.u32().name("refunded_stars_amount"),
  refundedElmAmount: __t.u32().name("refunded_elm_amount"),
  telegramPaymentChargeId: __t.string().name("telegram_payment_charge_id"),
  invoicePayload: __t.string().name("invoice_payload"),
  balanceKind: __t.string().name("balance_kind"),
  status: __t.string(),
  createdAtMicros: __t.u64().name("created_at_micros"),
  paidAtMicros: __t.option(__t.u64()).name("paid_at_micros"),
  creditedAtMicros: __t.option(__t.u64()).name("credited_at_micros"),
  refundRequestedAtMicros: __t.option(__t.u64()).name("refund_requested_at_micros"),
  refundedAtMicros: __t.option(__t.u64()).name("refunded_at_micros"),
  updatedAtMicros: __t.u64().name("updated_at_micros"),
});
